import React from 'react'
import Head from 'next/head';
import s from './Layout.module.scss'
import { IMainLayoutProps } from '../../types/mainLayout';
import Link from 'next/link';
import { network } from '../../constants/network';
import classNames from 'classnames';


export default function Layout({ title, children }: IMainLayoutProps) {
    return (
        <div className={s.layout}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={classNames(s.nav,"container")}>
                <Link href={"/"}><a>Home</a></Link>
                <Link href={"/works"}><a>Works</a></Link>
                <Link href={"/blog"}><a>Blog</a></Link>
            </nav>
            <main className={s.main}>
                {children}
            </main>
            <footer className={classNames(s.footer,"container")}>
                <div className={s.items}>
                    {
                        network.map(s => (
                            <a key={s.id} href={s.href} target="_blank">
                                <img src={s.icon.src} alt="Logo" />
                            </a>
                        ))
                    }
                </div>
                <h4 className={s.text}>
                    Copyright ©2020 All rights reserved
                </h4>
            </footer>
        </div>
    )
}
